edit ri.yml

diff --git a/.github/workflows/bus-management/Delete-Bus.yml b/.github/workflows/bus-management/Delete-Bus.yml
--- a/.github/workflows/bus-management/Delete-Bus.yml
+++ b/.github/workflows/bus-management/Delete-Bus.yml
@@ -1,9 +1,36 @@
-name: Register Bus Workflow
+name: CI/CD for DeleteBus
+
 on:
-  workflow_call: # INDISPENSABLE
+  workflow_call:
+    inputs:
+      docker-repo-name:
+        required: true
+        type: string
+    secrets:
+      DOCKER_USERNAME:
+        required: true
+      DOCKER_PASSWORD:
+        required: true
+
+permissions:
+  contents: read
+
 jobs:
-  Delete:
+  build-and-push-image:
     runs-on: ubuntu-latest
     steps:
-      - name: Register bus logic
-        run: echo "Registering bus..."
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Build and push Docker image for RegisterBus
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          REPO_NAME="${{ inputs.docker-repo-name }}"
+          echo "Repo name: $REPO_NAME"
+          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "ERROR: Invalid repository name."
+            exit 1
+          fi
+          DOCKERFILE_PATH="./BusManagement/DeleteBus/Dockerfile"
+          CONTEXT_PATH="./BusManagement/DeleteBus"
+          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t "${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest" "$CONTEXT_PATH" --push
