Edit ymls

diff --git a/BusManagement/RegisterBus/.github/workflows/cd.yml b/BusManagement/RegisterBus/.github/workflows/cd.yml
--- a/BusManagement/RegisterBus/.github/workflows/cd.yml
+++ b/BusManagement/RegisterBus/.github/workflows/cd.yml
@@ -1,33 +1,28 @@
-name: CI/CD Pipeline for Docker
+name: CI/CD for RegisterBus
 
 on:
-  workflow_call:
-    inputs:
-      docker_username:
-        required: true
-      docker_password:
-        required: true
-      repository_name:
-        required: true
+  push:
+    branches: ["QA"]
 
 permissions:
-  actions: read
   contents: read
 
 jobs:
-  login-and-push:
+  build-and-push-image:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ inputs.docker_username }}
-          password: ${{ inputs.docker_password }}
-
-      - name: Build and Push Docker Image
+      - name: Build and push Docker image for RegisterBus
         run: |
-          docker build -t ${{ inputs.docker_username }}/${{ inputs.repository_name }}:latest .
-          docker push ${{ inputs.docker_username }}/${{ inputs.repository_name }}:latest
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          REPO_NAME="${{ secrets.DOCKER_REPOSITORY_NAME_REGISTERBUS }}"
+          echo "Repo name: $REPO_NAME"
+          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "ERROR: Invalid repository name."
+            exit 1
+          fi
+          DOCKERFILE_PATH="./BusManagement/RegisterBus/Dockerfile"
+          CONTEXT_PATH="./BusManagement/RegisterBus"
+          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest "$CONTEXT_PATH" --push
