Add cd.yml of ViewBusDetails

diff --git a/.github/workflows/ri.yml b/.github/workflows/ri.yml
--- a/.github/workflows/ri.yml
+++ b/.github/workflows/ri.yml
@@ -2,7 +2,7 @@ name: Registry image
 
 on:
   push:
-    branches: ["QA"]
+    branches: ["dev"]
 
 permissions:
   contents: read
@@ -63,4 +63,24 @@ jobs:
           fi
           DOCKERFILE_PATH="./BusManagement/UpdateBusAvailability/Dockerfile"
           CONTEXT_PATH="./BusManagement/UpdateBusAvailability"
+          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest "$CONTEXT_PATH" --push
+
+
+  ViewBusDetails:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Build and push Docker image for ViewBusDetails
+        run: |
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          REPO_NAME="${{ secrets.DOCKER_REPOSITORY_NAME_BUS_VIEW }}"
+          echo "Repo name: $REPO_NAME"
+          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "ERROR: Invalid repository name."
+            exit 1
+          fi
+          DOCKERFILE_PATH="./BusManagement/ViewBusDetails/Dockerfile"
+          CONTEXT_PATH="./BusManagement/ViewBusDetails"
           docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest "$CONTEXT_PATH" --push
