Edit ymls

diff --git a/.github/workflows/ri.yml b/.github/workflows/ri.yml
--- a/.github/workflows/ri.yml
+++ b/.github/workflows/ri.yml
@@ -8,30 +8,40 @@ permissions:
   contents: read
 
 jobs:
-  trigger-registerbus-cd:
+  registerbus:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Trigger RegisterBus CD pipeline
-        uses: peter-evans/workflow-dispatch@v1
-        with:
-          repository: ${{ github.repository }}
-          workflow: .github/workflows/cd.yml
-          ref: refs/heads/QA
-          inputs: # Si es necesario, puedes definir inputs aquí
+      - name: Build and push Docker image for RegisterBus
+        run: |
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          REPO_NAME="${{ secrets.DOCKER_REPOSITORY_NAME_REGISTERBUS }}"
+          echo "Repo name: $REPO_NAME"
+          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "ERROR: Invalid repository name."
+            exit 1
+          fi
+          DOCKERFILE_PATH="./BusManagement/RegisterBus/Dockerfile"
+          CONTEXT_PATH="./BusManagement/RegisterBus"
+          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest "$CONTEXT_PATH" --push
 
-  trigger-deletebus-cd:
+  deletebus:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Trigger DeleteBus CD pipeline
-        uses: peter-evans/workflow-dispatch@v1
-        with:
-          repository: ${{ github.repository }}
-          workflow: .github/workflows/cd.yml
-          ref: refs/heads/QA
-          inputs: # Si es necesario, puedes definir inputs aquí
+      - name: Build and push Docker image for DeleteBus
+        run: |
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          REPO_NAME="${{ secrets.DOCKER_REPOSITORY_NAME_DELTEBUS }}"
+          echo "Repo name: $REPO_NAME"
+          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "ERROR: Invalid repository name."
+            exit 1
+          fi
+          DOCKERFILE_PATH="./BusManagement/DeleteBus/Dockerfile"
+          CONTEXT_PATH="./BusManagement/DeleteBus"
+          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest "$CONTEXT_PATH" --push
